# Sign Up and Navigation
signUp=//a[@id='logged-out-signup']
login=//a[@id='logged-out-login']
emailInput=//input[@id='email']
passwordInput=//*[@id='password']
submitButton=/html/body/div/div/div/div/form/button

# Products Menu Elements
productsMenu=//a[@aria-controls='mega-sub-menu-118']
herokuPlatform=//span[text()='Heroku Platform']
herokuAI=//span[text()='Heroku AI']
herokuDataServices=//span[text()='Heroku Data Services']
herokuEnterprise=//span[text()='Heroku Enterprise']
herokuSuccess=//span[text()='Heroku Success']
herokuElementsMarketplace=//span[text()='Heroku Elements Marketplace']

# Developers Menu Elements
developersMenu=//a[@aria-controls='mega-sub-menu-170']
devCenter=//span[text()='Dev Center']
devCurrentPage=//a[@aria-current='page']
